### ISSUE TITLE
Additional dependencies shouldn't be needed 

### ISSUE THREAD

**Issue by blade2005** [biomejs/pre-commit#5]
If in the `package.json` you include the version of `biome` you don't need to add the `additional_dependencies` line.

https://pre-commit.com/#node

Whenever a new version of biome is released on npm, bump the version in this repo and make a new tag.

It would make the tags on this repo line up mostly with the primary repo and I would add a release number on it,

for example for npmjs version `1.8.3` this repo would have a tag `v1.8.3-1`. And if independent changes need to be made to this repo, then you would increment the release version.

**Comment by blade2005** [comment]
I see why it's needed. 

Because it's written in rust but uses a monorepo structure, which I don't see that pre-commit has any support for. Basically would need to point the hook to `crates/biome_cli/Cargo.toml` which doesn't look feasible.

Then for node, because it's not in the packages itself it is incredibly difficult if not impossible due to pre-commit expecting it to be in the package.

**Comment by ematipico** [comment]
It isn't safe. Users might use `setup-biome`, or install the binary from other sources. We can't assume that Biome comes only from npm

**Comment by flying-sheep** [comment]
What do you mean “safe”? `pre-commit` is designed to be an environment manager. This also makes it work with `pre-commit.ci`. 

The above way of using biome is what the four hooks in this repo are for. I know this since this repository also has a README header

> ## Using biome with a local pre-commit hook

which describes how to define a `local-biome-check` hook that uses a biome not installed by pre-commit (but by a local npm, `setup-biome` or something else)
